name       : woff-tools
version    : 1.0
release    : 2
source     :
    - https://people.mozilla.org/~jkew/woff/woff-code-latest.zip : 7713630d2f43320a1d92e2dbb014ca3201caab1dd4c0ab92816016824c680d96
license    :
    - GPL-2.0
    - MPL-1.1
    - LGPL-2.1
summary    : Convert/Unconvert TrueType/OpenType fonts to WOFF format
component  : office
description: |
    Convert/Unconvert TrueType/OpenType fonts to WOFF format
build      : |
    %make
install    : |
    install -dm755 $installdir/usr/bin/
    install -Dm755 $workdir/sfnt2woff $installdir/usr/bin/sfnt2woff
    install -Dm755 $workdir/woff2sfnt $installdir/usr/bin/woff2sfnt
